"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { IconSparkles, IconCopy, IconCheckCircle } from "@/components/ui/icons";
import { generateFollowUpAction } from "@/lib/actions/leads";

export function GenerateFollowUpButton({ leadId }: { leadId: string }) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState("");
  const [source, setSource] = useState<"mock" | "ai" | null>(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function handleGenerate() {
    setError(null);
    startTransition(async () => {
      try {
        const result = await generateFollowUpAction(leadId);
        setMessage(result.message);
        setSource(result.source);
        setCopied(false);
        setOpen(true);
        router.refresh();
      } catch {
        setError("Couldn't generate a message. Please try again.");
      }
    });
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(message);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setError("Couldn't copy to clipboard.");
    }
  }

  return (
    <>
      <Button size="sm" onClick={handleGenerate} disabled={isPending}>
        <IconSparkles className="h-4 w-4" />
        {isPending ? "Generating…" : "Generate Follow-Up Message"}
      </Button>
      {error ? <p className="mt-2 text-sm text-danger">{error}</p> : null}

      <Modal open={open} onClose={() => setOpen(false)} title="Follow-Up Message">
        <div className="space-y-4">
          <div className="rounded-[var(--radius-control)] border border-line bg-paper p-4">
            <p className="whitespace-pre-wrap text-sm leading-relaxed text-ink">{message}</p>
          </div>
          <p className="text-xs text-ink-faint">
            {source === "ai"
              ? "Generated by your connected AI provider."
              : "Generated with LeadLoop's built-in demo generator — connect an AI provider in Settings to personalize further."}
          </p>
          <div className="flex items-center justify-end gap-3">
            <Button variant="secondary" size="sm" onClick={() => setOpen(false)}>
              Close
            </Button>
            <Button size="sm" onClick={handleCopy}>
              {copied ? <IconCheckCircle className="h-4 w-4" /> : <IconCopy className="h-4 w-4" />}
              {copied ? "Copied!" : "Copy Message"}
            </Button>
          </div>
        </div>
      </Modal>
    </>
  );
}
